Latin_America_To_USA=<body><img src="Newspaper_Brazil.png"/></body>

Australia_To_USA=<body><img src="Newspaper_Australia_USA.png"/></body>

Moscow_Falls=<body><img src="Newspaper_Moscow_Falls.png"/></body>

Axis_Win=<body>The Axis Win!</body>

Allies_Win=<body>The Allies Win!</body>

Newspaper=<body><img src="Newspaper.png"/></body>

Germany_War_USSR=<body><img src="Newspaper_Germany_War_USSR.png"/></body>

Germany_War_USA=<body><img src="Newspaper_Germany_War_USA.png"/></body>

Japan_War_USSR=<body><img src="Newspaper_Japan_War_USSR.png"/></body>

Japan_War_USA=<body><img src="Newspaper_Japan_War_USA.png"/></body>

Japan_War_UK=<body><img src="Newspaper_Japan_War_UK.png"/></body>

Italy_War_USSR=<body><img src="Newspaper_Italy_War_USSR.png"/></body>

Italy_War_USA=<body><img src="Newspaper_Italy_War_USA.png"/></body>

USSR_War_Germany=<body><img src="Newspaper_USSR_War_Germany.png"/></body>

USSR_War_Japan=<body><img src="Newspaper_USSR_War_Japan.png"/></body>

USSR_War_Italy=<body><img src="Newspaper_USSR_War_Italy.png"/></body>

USA_War_Germany=<body><img src="Newspaper_USA_War_Germany.png"/></body>

USA_War_Japan=<body><img src="Newspaper_USA_War_Japan.png"/></body>

USA_War_Italy=<body><img src="Newspaper_USA_War_Italy.png"/></body>

UK_War_Japan=<body><img src="Newspaper_UK_War_Japan.png"/></body>

Axis_War_Spain=<body><img src="Newspaper_Axis_War_Spain.png"/></body>

Allies_War_Spain=<body><img src="Newspaper_Allies_War_Spain.png"/></body>

Axis_War_Sweden=<body><img src="Newspaper_Axis_War_Sweden.png"/></body>

Allies_War_Sweden=<body><img src="Newspaper_Allies_War_Sweden.png"/></body>

Axis_War_Turkey=<body><img src="Newspaper_Axis_War_Turkey.png"/></body>

Allies_War_Turkey=<body><img src="Newspaper_Allies_War_Turkey.png"/></body>

Captain_America_Berlin=<body><img src="Newspaper_Captain_America_Berlin.png"/></body>

Final_Countdown=<body><img src="Newspaper_Final_Countdown.png"/></body>

Red_Baron=<body><img src="Newspaper_Red_Baron.png"/></body>

Game_Title=<body><img src="Game_Title.png"/></body>
